# Generated by Django 6.0 on 2026-01-22 01:39

import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_document_type_alter_dogovor_payment_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[validators.validate_file_extension, validators.validate_file_size], verbose_name='Скан документа'),
        ),
    ]
