# Generated by Django 6.0 on 2026-05-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_abiturient_enrollment_date_abiturient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='dogovor',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
