# Generated by Django 6.0 on 2026-05-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_dogovor_is_paid_dogovor_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturient',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер личного дела'),
        ),
    ]
